### ISSUE TITLE
Crouton failed to install because of a permission problem.

### ISSUE THREAD

**Issue by Morcovka** [MercuryWorkshop/fakemurk#31] opened 2023-04-12 02:35 UTC
- [X] I am not reporting an issue unrelated to the fakemurk utilities.
- [X] I am not reporting an issue related to a borked system.
- [X] I am not an angry sysadmin.
- [x] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
Can't install crouton because of permission problem.

# TERMINAL OUTPUT (if any)
![image](https://user-images.githubusercontent.com/46952086/231332663-0a856704-c178-421e-99ee-00809c4f282a.png)

Downloading latest crouton installer...
############################################################################################################################################## 100.0%
ln: failed to create symbolic link '/usr/local/chroots': Read-only file system
Connection to 127.0.0.1 closed.
touch: cannot touch '/mnt/stateful_partition/crouton': Permission denied

# ADDITIONAL NOTES
Before that, my chromebook automatically reverted to being enrolled for no reason and my previous fakemurk installation had crouton. It was very weird and it might have something to do with the last update. I recovered to 91 after my chromebook reverted for 0 reasons, unrolled chromebook, and upgraded to v105. After that I tried to install crouton but it failed.

**Comment by Morcovka** [comment] 2023-04-12 02:38
Also I accidentally enrolled before installing fakemurk, forgot to add that in additional notes. Maybe that's the problem. I still had access to shell and sudo su despite accidentally using my school email on login.

**Comment by CoolElectronics** [comment] 2023-04-12 17:54
duplicate of #19, not a fakemurk issue but there's no solution outside recovery

**Closed** 2023-04-12 17:54 UTC
