### ISSUE TITLE
exit code 32

### ISSUE THREAD

**Issue by dabeast402** [MercuryWorkshop/fakemurk#10] opened 2023-03-13 02:46 UTC
- [] I am not reporting an issue unrelated to the fakemurk utilities.
- [] I am not reporting an issue related to a borked system.
- [] I am not an angry sysadmin.
- [] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
im on 105 on an unenrolled chromebook. I redid the shimmer thing, but still no use. 
# TERMINAL OUTPUT (if any)
  \ \__\   \ \__\ \__\ \__\\ \__\ \_______\ \__\    \ \__\ \_______\ \__\\ _\\ \__\\ \__\
    \|__|    \|__|\|__|\|__| \|__|\|_______|\|__|     \|__|\|_______|\|__|\|__|\|__| \|__|

THIS IS FREE SOFTWARE! if you paid for this, you have been scammed and should demand your money back

fakemurk - a tool made by Mercury Workshop to spoof verified boot while enrolled
you can find this script, its explanation, and documentation here: https://github.com/MercuryWorkshop/fakemurk

WARNING: THIS SCRIPT WILL REQUIRE THE REMOVAL OF ROOTFS VERIFICATION, AND THE DISABLING OF AUTOUPDATES
THIS MEANS THAT IF YOU EVER TURN OFF DEVMODE, YOUR SYSTEM WILL BE BRICKED UNTIL RECOVERY

WE ARE NOT RESPONSIBLE FOR DAMAGE, YOU BEING STUPID AND MISUSING THIS, OR GETTING IN TROUBLE
DO YOU UNDERSTAND??

(enter to proceed, ctrl+c to quit)

Would you like to enable rootfs restore? It will add an option to quickly revert all changes and re-enroll. (Y/n)y
----- stage 1: grabbing disk configuration -----
target kern is 2@/dev/mmcblk0p2
target root is 3@/dev/mmcblk0p3

backup kern is 4@/dev/mmcblk0p4
backup root is 5@/dev/mmcblk0p5
----- stage 2: patching target rootfs -----
removing rootfs verification on target kernel /dev/mmcblk0p2
mount: /tmp/rootmnt: /dev/mmcblk0p3 already mounted or mount point busy.
"echo "----- stage 2: patching target rootfs -----"" command failed with exit code 32. THIS IS A BUG, REPORT IT HERE https://github.com/MercuryWorkshop/fakemurk
# ADDITIONAL NOTES

**Comment by CoolElectronics** [comment] 2023-03-13 21:13
duplicate of #5

**Closed by CoolElectronics** 2023-03-13 21:13 UTC
