### ISSUE TITLE
ADB Debugging not able to be enabled in Android Settings.

### ISSUE THREAD

**Issue by kxtzownsu** [MercuryWorkshop/fakemurk#33] opened 2023-04-17 04:51 UTC
- [x] I am not reporting an issue unrelated to the fakemurk utilities.
- [x] I am not reporting an issue related to a borked system.
- [x] I am not an angry sysadmin.
- [x] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
Whenever I go to enable ADB Debugging in Android Developer Settings, it is blocked due to the fact ARC thinks the system is in verified mode.

# TERMINAL OUTPUT (if any)
localhost ~ # adb connect arc
unable to connect to arc:5555: Connection timed out
localhost ~ # 

# ADDITIONAL NOTES
![image](https://user-images.githubusercontent.com/116377025/232379956-1ac481cb-b963-446e-8fd9-00d170cb11a3.png)
![image](https://user-images.githubusercontent.com/116377025/232380050-45d75e59-0576-4bd8-a609-95db40d3af51.png)

**Comment by CoolElectronics** [comment] 2023-05-07 17:32
duplicate of #24

**Closed by CoolElectronics** 2023-05-07 17:32 UTC
