### ISSUE TITLE
Cannot install APKs

### ISSUE THREAD

**Issue by kxtzownsu** [MercuryWorkshop/fakemurk#26] opened 2023-04-09 08:02 UTC
- [] I am not reporting an issue unrelated to the fakemurk utilities.
- [x] I am not reporting an issue related to a borked system.
- [X] I am not an angry sysadmin.
- [] I have attached the complete and full output from the terminal

# ISSUE DESCRIPTION
Using Fakemurk, the Package Manager thinks the OS is in verified mode and will not let APKs be installed.

# TERMINAL OUTPUT (if any)
N/A

# ADDITIONAL NOTES
![image](https://user-images.githubusercontent.com/116377025/230761382-9a01cfa2-4db5-4c41-ab82-8e26c9e80805.png)

**Comment by CoolElectronics** [comment] 2023-04-10 18:10
duplicate of #24

**Closed by CoolElectronics** 2023-04-10 18:10 UTC

**Comment by kxtzownsu** [comment] 2023-04-14 04:11
Even on that issue, theres no solution that works.
